version: '3.3'
services:
    zap:
        depends_on:
            - web
        build: ./zap
        container_name: zap
        working_dir: /zap
        #links:
        #- 'web:web'
        environment:
            - PATH=/bin:/usr/bin/
            - CHECKER=/zap/checker
            - WEB_IP= web
            - WEB_PORT= 8080
        volumes:
            - '/home/runner/work/testWebServer/testWebServer/.github/actions/container/DAST/zap/:/zap/checker'
        networks:
            - CDnetwork
        entrypoint:
            - 'bash'
            - 'ifconfig'
            - '/zap/checker/Start.sh'
    web:
        build: ./project
        container_name: web
        working_dir: /github/workspace
        environment:
            - PATH=/bin:/usr/bin/
            - CHECKER=/github/workspace/checker
            - PORT=800000
        volumes:
            - '/home/runner/work/testWebServer/testWebServer:/github/workspace'
            - '/home/runner/work/testWebServer/testWebServer/.github/actions/container/DAST/project/:/github/workspace/checker'
        networks:
            - CDnetwork
        entrypoint:
            - 'bash'
            - 'ifconfig'
            - '/github/workspace/checker/Start.sh'
networks:
    CDnetwork:
       driver: bridge
