name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: ls
      run: |
        ls -al
    - name: pwd
      run: |
        pwd
    # - name: cppcheck
    #   uses: deep5050/cppcheck-action@master
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN}}
    - name: dockerCompose
      run: |
        docker-compose -f .github/actions/container/UniteTest/docker-compose.yml up --build
