name: C/C++ CD

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: ls
      run: |
        ls -al
    - name: pwd
      run: |
        pwd
    - name: dockerCompose
      run: |
        docker-compose -f .github/actions/container/DAST/docker-compose.yml up --build 
        
        
        # --exit-code-from zap
